services:
  - type: web
    name: nebula-tasks-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false

  - type: static
    name: nebula-tasks-web
    rootDir: vite-project
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://nebula-tasks-api.onrender.com
